version: '3.6'

# TODO Replace any javapi or dockerdonegal entry with your dockerhub account
services:
   jenkins:
     image: javapi/dd-jenkins:latest
     user: root
     ports:
       - 8080:8080
     deploy:
       replicas: 1
       restart_policy:
         condition: any
     networks:
     - dd-network
     volumes:
       - jenkins_home:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
       - /var/run/docker.sock:/var/run/docker.sock

networks:
  dd-network:
    external: true

volumes:
  jenkins_home:
  sonarqube_bundled_plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  mongo: