server:
  port: 8081
  servlet:
    context-path: /ninja

spring:
  application:
    name: ninja-belt
  data:
    mongodb:
      host: ninja.dockerdonegal.ie
      port: 27017
      database: ninja
      username: ninja
      password: ninja